# Generated by Django 6.0 on 2026-08-29 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author_alter_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 29, 22, 47, 28, 537186, tzinfo=datetime.timezone.utc)),
        ),
    ]
